apiVersion: apps/v1
kind: Deployment
metadata:
  name: oglasojad
  namespace: oglasojad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oglasojad
  template:
    metadata:
      labels:
        app: oglasojad
    spec:
      containers:
      - name: oglasojad
        image: miki023/oglasojad:latest
        env:
          - name: spring.datasource.url
            valueFrom:
              configMapKeyRef:
                name: oglasojad-config
                key: DATABASE_URL
          - name: spring.datasource.username
            valueFrom:
              configMapKeyRef:
                name: oglasojad-config
                key: POSTGRES_USERNAME
          - name: spring.datasource.password
            valueFrom:
              secretKeyRef:
                name: oglasojad-secret
                key: POSTGRES_PASSWORD
          - name: spring.jpa.show-sql
            value: "false"
        ports:
          - containerPort: 8080

