apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: oglasojad
spec:
  serviceName: "oglasojad-db"
  replicas: 1
  selector:
    matchLabels:
      app: oglasojad-db
  template:
    metadata:
      labels:
        app: oglasojad-db
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "oglasojad-db"
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-storage-postgres-0
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
