apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: oglasojad
spec:
  serviceName: "oglasojad-db"
  replicas: 1
  selector:
    matchLabels:
      app: oglasojad-db
  template:
    metadata:
      labels:
        app: oglasojad-db
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: oglasojad-config
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oglasojad-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: oglasojad-config
                  key: DB_NAME
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-storage-postgres-0
        - name: init-script
          configMap:
            name: mysql-initdb-config
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

